FROM openjdk:17-jdk
# Set the working directory inside the container
WORKDIR /app
# Copy the JAR file into the container at /app/app.jar
COPY target/hello-0.0.1-SNAPSHOT.jar app.jar
# Expose port 8080 to the host
EXPOSE 8080
# Set the entrypoint to run the application when the container starts
ENTRYPOINT ["java", "-jar", "app.jar"]
