# Use the official Maven image as the build environment
FROM maven:3.8.3-openjdk-17-slim AS builder

# Set the working directory to /app
WORKDIR /app

# Copy the pom.xml and other necessary files to the container
COPY pom.xml .
COPY src ./src

# Build the application using Maven
RUN mvn clean package -DskipTests

# Use a smaller, runtime image for Java applications
FROM openjdk:17-jdk-slim

# Set the working directory to /app
WORKDIR /app

# Copy the built JAR file from the builder stage to the container
COPY --from=builder /app/target/hello-0.0.1-SNAPSHOT.jar hello-0.0.1-SNAPSHOT.jar

# Expose the port on which your application listens (if applicable)
EXPOSE 8080

# Start the Java application
CMD ["java", "-jar", "hello-0.0.1-SNAPSHOT.jar"]
